site_name: Q* - RPG System
repo_url: https://github.com/ehrpg/qstar
site_author: "@n0la, @johannes-z"
dev_addr: 127.0.0.1:8001

theme:
    name: null
    custom_dir: material

    # 404 page
    static_templates:
        - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    feature:
        tabs: true
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/images/favicon.png
    logo:
        icon: "\u269D"

extra_css:
    - css/extra.css
    - css/font-awesome.min.css
    - css/ehicons.css
    - css/game-icons.css
extra_javascript:
    - js/sorttable.js
    - js/extra.js

markdown_extensions:
    - pymdownx.details
    - pymdownx.smartsymbols
    - pymdownx.tilde
    - pymdownx.caret
    - pymdownx.extrarawhtml
    - markdown.extensions.def_list
    - codehilite
    - admonition
    - attr_list
    - smarty
    - footnotes
    - markdown_include.include:
        base_path: './'
    - toc:
        permalink: True

pages:
    - Q*:
        - Introduction: 'index.md'
        - Quick Start Rules: 'quick-start.md'
        # - notes: 'notes.md'

        - Character:
            - Character Creation: 'character-creation.md'

            - Races: 'character/races.md'
            - Character: 'character/index.md'
            - Skills: 'character/skills.md'
            - Perks: 'character/perks.md'
            - Flaws: 'character/flaws.md'
            - Equipment: 'character/equipment.md'

        - Crisis: 'crisis.md'
        - Stunts: 'stunts.md'

        - Vehicles & Vessels:
            - Vessels: 'vessel/index.md'
            - Perks & Flaws: 'vessel/perks-flaws.md'
            - Combat: 'vessel/combat.md'
            - Stunts: 'vessel/stunts.md'
            - Equipment: 'vessel/equipment.md'

    - Setting — Q*:
        - Introduction: 'settings/qstar/index.md'

    - Setting — S.T.A.L.K.E.R.:
        - Introduction: 'settings/stalker/index.md'
