site_name: Q* - RPG
repo_url: https://github.com/ehrpg/qstar
site_author: "@n0la, @johannes-z"
dev_addr: 127.0.0.1:8001

theme:
    name: null
    custom_dir: material

    # 404 page
    static_templates:
        - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    feature:
        tabs: true
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/images/favicon.png
    logo:
        icon: "\uE80C"

extra_css:
    - css/extra.css
    - css/font-awesome.min.css
    - css/ehicons.css
    - css/game-icons.css
extra_javascript:
    - js/extra.js

markdown_extensions:
    - codehilite
    - admonition
    - attr_list
    - smarty
    - footnotes
    - toc:
        permalink: True

pages:
    - Q*:
        - Introduction: 'index.md'
        - Character: 'character.md'
        - Skills: 'skills.md'
        - Perks & Flaws: 'perks_flaws.md'
        - Combat: 'combat.md'
        - Equipment: 'equipment.md'

    - Vehicles & Vessels:
        - Vessel: 'vessel/vessel.md'
        - Combat: 'vessel/combat.md'
        - Equipment: 'vessel/equipment.md'

    - Setting — Q*:
        - Introduction: 'settings/qstar/index.md'

    - Setting — S.T.A.L.K.E.R.:
        - Introduction: 'settings/stalker/index.md'
