site_name: Q* - RPG System
repo_url: https://github.com/ehrpg/qstar
site_author: "@n0la, @johannes-z"
dev_addr: 127.0.0.1:8001

theme:
    name: null
    custom_dir: material

    # 404 page
    static_templates:
        - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    feature:
        tabs: true
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/images/favicon.png
    logo:
        icon: "\u269D"

extra_css:
    - _css/extra.css
    - _css/font-awesome.min.css
    - _css/game-icons.css
extra_javascript:
    - _js/sorttable.js

markdown_extensions:
    - pymdownx.snippets:
        base_path: docs/
    - pymdownx.details
    - pymdownx.smartsymbols
    - pymdownx.tilde
    - pymdownx.caret
    - pymdownx.extrarawhtml
    - pymdownx.superfences
    - markdown.extensions.def_list
    - codehilite
    - admonition
    - attr_list
    - smarty
    - footnotes
    - toc:
        permalink: True

nav:
    - Q*:
        - Introduction: 'index.md'

        - Characters:
            - Character: 'character/index.md'
            - Races: 'character/races.md'
            - Skills: 'character/skills.md'
            - Talents: 'character/talents.md'

        - Equipment:
            - Equipment: 'equipment/index.md'
            - Weapons: 'equipment/weapons.md'
            - Armour & Outfits: 'equipment/armour-outfits.md'
            - Utilities & Miscellaneous: 'equipment/util-misc.md'

        - Crisis: 'crisis.md'

        - NPCs:
            - NPCs: 'npc/index.md'

        - Vehicles & Vessels:
            - Vessel: 'vessel/index.md'
            - Talents: 'vessel/talents.md'
            - Combat: 'vessel/combat.md'
            - Equipment: 'vessel/equipment.md'

        - Character Creation*: 'character/character-creation.md'
        - Quick Start Rules*: 'quick-start.md'

    - Setting — Q*:
        - Introduction: 'settings/qstar/index.md'

    - Setting — S.T.A.L.K.E.R.:
        - Introduction: 'settings/stalker/index.md'
