site_name: QStar - RPG
repo_url: https://github.com/ehrpg/qstar
site_author: "@n0la, @johannes-z"
dev_addr: 127.0.0.1:8001

theme:
  name: 'material'
extra_css:
    - css/extra.css
    - css/font-awesome.min.css
    - css/ehicons.css
extra_javascript:
    - js/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - smarty
  - toc:
      permalink: True

pages:
- Introduction: 'index.md'
- QStar: 
    - Rules: 'qstar.md'
    - Perks: 'perks.md'
    - Equipment: 'equipment.md'
    - Task DCs: 'taskdcs.md'
    - Vessels: 'vessels.md'

- S.T.A.L.K.E.R. Setting:
    - Rules: 'settings/stalker/rules.md'
    - Equipment: 'settings/stalker/equipment.md'
    - Perks: 'settings/stalker/perks.md'
